env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb-base
  - plugin:react-hooks/recommended
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - functional
  - prettier
rules:
  import/extensions: 0
  no-console: 0
  react/prop-types: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statement: 0
  react/function-component-definition: 0
  no-param-reassign: ['error', { 'props': false }]
  prettier/prettier: error
